# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"

  # Packages
  - package-ecosystem: "npm"
    directory: "/packages/lorc"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/tsconfig"
    schedule:
      interval: "daily"

  # Apps
  - package-ecosystem: "npm"
    directory: "/apps/anzelmo"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/bapta"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/buffalo"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/caffeino"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/oak"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/startino"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/template"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/wonderlee"
    schedule:
      interval: "daily"
