services:
  app:
    image: app
    build:
      context: .
      dockerfile: Containerfile.dev
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
