name: Deploy to Remote Repo

on:
  workflow_dispatch:
  push:
    branches:
      - alpha

jobs:
  deploy:
    name: Building ${{ matrix.project.name }} with Bun version ${{ matrix.bun-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [ latest ]
        project:
          [
            {
                name: LoRC,
                id: lorc,
                path: packages/lorc,
                domain: lorc.futi.no
              },
            {
                name: Allheim,
                id: allheim,
                path: apps/allheim,
                domain: allheim.futi.no
              },
            {
                name: Anzelmo,
                id: anzelmo,
                path: apps/anzelmo,
                domain: anzelmo.futi.no
              },
            {
                name: Bapta,
                id: bapta,
                path: apps/bapta,
                domain: bapta.futi.no
              },
            {
                name: Eksno,
                id: eksno,
                path: apps/eksno,
                domain: eksno.com
              },
            {
                name: GGSoccer,
                id: ggsoccer,
                path: apps/ggsoccer,
                domain: ggsoccer.futi.no
              },
            {
                name: Liberole,
                id: liberole,
                path: apps/liberole,
                domain: liberole.futi.no
              },
            {
                name: Template,
                id: template,
                path: apps/template,
                domain: template.futi.no
              },
            {
                name: Webskite,
                id: website,
                path: apps/website,
                domain: futki.no
              }
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun with version ${{ matrix.bun-version }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun i

      - name: Build Project
      - run: |
          cd ${{ matrix.project.path }}
          bun run build
