name: Build Projects

on:
  workflow_dispatch:
  pull_request:
    branches:
      - alpha

jobs:
  buildall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
  build:
    name: Building ${{ matrix.project.name }} with Bun ${{ matrix.bun-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bun-version: [ latest ]
        project:
          - {
              name: LoRC,
              id: lorc,
              path: packages/lorc,
              domain: lorc.futi.no,
            }
          - {
              name: Allheim,
              id: allheim,
              path: apps/allheim,
              domain: allheim.futi.no,
            }
          - {
              name: Anzelmo,
              id: anzelmo,
              path: apps/anzelmo,
              domain: anzelmo.futi.no,
            }
          - {
              name: Bapta,
              id: bapta,
              path: apps/bapta,
              domain: bapta.futi.no,
            }
          - {
              name: Eksno,
              id: eksno,
              path: apps/eksno,
              domain: eksno.com,
            }
          - {
              name: GGSoccer,
              id: ggsoccer,
              path: apps/ggsoccer,
              domain: ggsoccer.futi.no,
            }
          - {
              name: Liberole,
              id: liberole,
              path: apps/liberole,
              domain: liberole.futi.no,
            }
          - {
              name: Website,
              id: website,
              path: apps/website,
              domain: futi.no,
            }
          - {
              name: Wonderlee,
              id: wonderlee,
              path: apps/wonderlee,
              domain: wonderlee.futi.no,
            }
          - {
              name: Template,
              id: template,
              path: apps/template,
              domain: template.futi.no,
            }
          - {
              name: Aitino,
              id: aitino,
              path: apps/aitino,
              domain: aitino.futi.no,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun with version ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: |
          cd ${{ matrix.project.path }}
          bun i # fails sometimes without this
          bun run build
