name: Deploy to Remote Repo

on:
  workflow_dispatch:
  push:
    branches:
      # Disabled until bun finished https://bun.sh/guides/install/cicd
      #      - 'alpha'

jobs:
  deploy:
    name: Deploying ${{ matrix.project.name }} to ${{ matrix.project.domain }} in https://github.com/Futino/${{ matrix.project.name }}@gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
        project:
          [
            { name: allheim, domain: allheim.futi.no },
            { name: anzelmo, domain: anzelmo.futi.no },
            { name: bapta, domain: bapta.futi.no },
            { name: eksno, domain: eksno.com },
            { name: ggsoccer, domain: ggsoccer.futi.no },
            { name: liberole, domain: liberole.futi.no },
            { name: web-template, domain: template.futi.no },
            { name: website, domain: futi.no }
          ]

    steps:
      # pnpm setup following https://pnpm.io/continuous-integration#github-actions
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.project.name }}
          pnpm i --no-frozen-lockfile

      - name: Build Monorepo
        run: |
          cd apps/${{ matrix.project.name }}
          pnpm build

      - name: Prepare for GitHub Pages
        run: |
          cd apps/${{ matrix.project.name }}
          echo -e "${{ matrix.project.domain }}" >> build/CNAME
          touch build/.nojekyll

      - name: Deploy to https://github.com/Futino/${{ matrix.project.name }}@gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: apps/${{ matrix.project.name }}/build # The folder the action should deploy.
          repository-name: Futino/${{ matrix.project.name }} # The repository the action should deploy to.
          target-folder: /
          clean: true
